/*
 * Copyright (c) 2017 Jon Carlson. All rights reserved.
 * Use of this source code is governed by the MIT license that can be found in the LICENSE file.
 */

CREATE SCHEMA s1;
CREATE TABLE s1.table13 (
    id1 integer,
    id2 bigint generated by default as identity,
    id3 integer generated by default as identity
);

CREATE SCHEMA s2;
CREATE TABLE s2.table13 (
    id1 integer generated by default as identity, -- drop identity
    id2 integer -- int to bigint, add identity
    -- add identity column
);
